=== Ebe66/Windows-Wahoo-Map-Creator-Osmosis/RenderTheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:tns="http://opensciencemap.org/rendertheme"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://opensciencemap.org/rendertheme" xml:lang="en">

    <!-- attribute types -->
    <xs:simpleType name="cap">
        <xs:restriction base="xs:string">
            <xs:enumeration value="butt" />
            <xs:enumeration value="round" />
            <xs:enumeration value="square" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="closed">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
            <xs:enumeration value="any" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:restriction base="xs:string">
            <xs:pattern value="#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="elementList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="node" />
            <xs:enumeration value="way" />
            <xs:enumeration value="any" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="selectorList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="first" />
            <xs:enumeration value="any" />
            <xs:enumeration value="when-matched" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fontFamily">
        <xs:restriction base="xs:string">
            <xs:enumeration value="default" />
            <xs:enumeration value="default_bold" />
            <xs:enumeration value="monospace" />
            <xs:enumeration value="sans_serif" />
            <xs:enumeration value="serif" />
            <xs:enumeration value="thin" />
            <xs:enumeration value="light" />
            <xs:enumeration value="medium" />
            <xs:enumeration value="black" />
            <xs:enumeration value="condensed" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fontStyle">
        <xs:restriction base="xs:string">
            <xs:enumeration value="bold" />
            <xs:enumeration value="bold_italic" />
            <xs:enumeration value="italic" />
            <xs:enumeration value="normal" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonNegativeFloat">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="src">
        <xs:restriction base="xs:string">
            <xs:pattern value="((file|assets):)?.+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="strokeDasharray">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="([0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)? *, *)*[0-9]+(\.[0-9]+)? *, *[0-9]+(\.[0-9]+)?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="textKey">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ele" />
            <xs:enumeration value="addr:housenumber" />
            <xs:enumeration value="addr_housenumber" /> <!-- Mapzen -->
            <xs:enumeration value="housenumber" /> <!-- OpenMapTiles -->
            <xs:enumeration value="name" />
            <xs:enumeration value="ref" />
        </xs:restriction>
    </xs:simpleType>

    <!-- style menu cat element -->
    <xs:complexType name="cat">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <!-- style menu name element -->
    <xs:complexType name="name">
        <xs:attribute name="lang" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>

    <!-- style menu overlay element -->
    <xs:complexType name="overlay">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <!-- style menu layer element -->
    <xs:complexType name="layer">
        <xs:sequence maxOccurs="1" minOccurs="0">
            <xs:element name="name" maxOccurs="unbounded" minOccurs="0" type="tns:name" />
            <xs:element name="cat" maxOccurs="unbounded" minOccurs="0" type="tns:cat" />
            <xs:element name="overlay" maxOccurs="unbounded" minOccurs="0" type="tns:overlay" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="parent" type="xs:string" use="optional" />
        <xs:attribute name="visible" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="enabled" default="false" type="xs:boolean" use="optional" />
    </xs:complexType>

    <!-- rendering instructions -->
    <xs:complexType name="area">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="id" default="0" type="xs:string" use="optional" />
        <xs:attribute name="use" default="0" type="xs:string" use="optional" />
        <xs:attribute name="src" type="tns:src" use="optional" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="fade" default="-1" type="xs:integer" use="optional" />
        <xs:attribute name="blend" default="-1" type="xs:integer" use="optional" />
        <xs:attribute name="blend-fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="mesh" default="false" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="caption">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="k" type="tns:textKey" use="required" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="font-family" default="default" type="tns:fontFamily" use="optional" />
        <xs:attribute name="style" default="normal" type="tns:fontStyle" use="optional" />
        <xs:attribute name="size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="bg-fill" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <!-- polygon area expressed as a ratio to tile area, e.g. 0.1 for 10% of tile area -->
        <xs:attribute name="area-size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <!-- priority for label placement, 0 = highest priority -->
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />
        <!-- symbol src name -->
        <xs:attribute name="symbol" type="tns:src" use="optional" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
    </xs:complexType>

    <xs:complexType name="circle">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="radius" type="tns:nonNegativeFloat" use="required" />
        <xs:attribute name="scale-radius" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="fill" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
    </xs:complexType>

    <xs:complexType name="line">
        <xs:attribute name="cat" type="xs:string" use="optional" />

        <!-- style: TODO only in style-line-->
        <xs:attribute name="id" default="0" type="xs:string" use="optional" />

        <!-- inherited style -->
        <xs:attribute name="use" default="0" type="xs:string" use="optional" />

        <xs:attribute name="src" type="tns:src" use="optional" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="width" default="0" type="xs:float" use="optional" />
        <!-- minimum scaled width to draw outline -->
        <xs:attribute name="min" default="0" type="xs:float" use="optional" />
        <xs:attribute name="dasharray" type="tns:strokeDasharray" use="optional" />
        <xs:attribute name="cap" default="round" type="tns:cap" use="optional" />
        <xs:attribute name="outline" default="" type="xs:string" use="optional" />
        <xs:attribute name="fade" default="-1" type="xs:integer" use="optional" />
        <xs:attribute name="blur" default="-1" type="xs:float" use="optional" />
        <xs:attribute name="fix" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="repeat-gap" default="200" type="xs:float" use="optional" />
        <xs:attribute name="repeat-start" default="30" type="xs:float" use="optional" />

        <!-- stipple repeat in 'pixel' -->
        <xs:attribute name="stipple" default="0" type="xs:integer" use="optional" />
        <!-- stipple color -->
        <xs:attribute name="stipple-stroke" default="#000000" type="tns:color" use="optional" />
        <!-- stipple width relative to line width, i.e 0.0-1.0 -->
        <xs:attribute name="stipple-width" default="0" type="xs:float" use="optional" />

    </xs:complexType>

    <xs:complexType name="text">
        <xs:attribute name="cat" type="xs:string" use="optional" />

        <xs:attribute name="id" default="0" type="xs:string" use="optional" />
        <xs:attribute name="use" default="0" type="xs:string" use="optional" />

        <xs:attribute name="k" default="name" type="tns:textKey" use="optional" />
        <xs:attribute name="dy" default="0" type="xs:float" use="optional" />
        <xs:attribute name="font-family" default="default" type="tns:fontFamily" use="optional" />
        <xs:attribute name="style" default="normal" type="tns:fontStyle" use="optional" />
        <xs:attribute name="size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="bg-fill" default="#00000000" type="tns:color" use="optional" />
        <xs:attribute name="fill" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke" default="#000000" type="tns:color" use="optional" />
        <xs:attribute name="stroke-width" default="0" type="tns:nonNegativeFloat" use="optional" />
        <xs:attribute name="caption" default="false" type="xs:boolean" use="optional" />
        <!-- polygon area expressed as a ratio to tile area, e.g. 0.1 for 10% of tile area -->
        <xs:attribute name="area-size" default="0" type="tns:nonNegativeFloat" use="optional" />
        <!-- priority for label placement, 0 = highest priority -->
        <xs:attribute name="priority" default="0" type="xs:integer" use="optional" />
    </xs:complexType>

    <xs:complexType name="symbol">
        <xs:attribute name="cat" type="xs:string" use="optional" />

        <xs:attribute name="id" default="0" type="xs:string" use="optional" />
        <xs:attribute name="use" default="0" type="xs:string" use="optional" />

        <xs:attribute name="src" type="tns:src" use="optional" />
        <xs:attribute name="symbol-width" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-height" type="xs:positiveInteger" use="optional" />
        <xs:attribute name="symbol-percent" type="xs:positiveInteger" use="optional" />

        <!-- symbols on lines -->
        <xs:attribute name="billboard" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="repeat" default="false" type="xs:boolean" use="optional" />
        <xs:attribute name="repeat-gap" default="200" type="xs:float" use="optional" />
        <xs:attribute name="repeat-start" default="30" type="xs:float" use="optional" />
        <xs:attribute name="rotate" default="true" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:complexType name="extrusion">
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="line-color" type="tns:color" use="optional" />
        <xs:attribute name="side-color" type="tns:color" use="required" />
        <xs:attribute name="top-color" type="tns:color" use="required" />
        <xs:attribute name="hsv-h" default="0" type="xs:double" use="optional" />
        <xs:attribute name="hsv-s" default="1" type="xs:double" use="optional" />
        <xs:attribute name="hsv-v" default="1" type="xs:double" use="optional" />
        <!-- 12m default -->
        <xs:attribute name="default-height" default="12" type="xs:positiveInteger" use="optional" />
    </xs:complexType>

    <!-- match elements -->
    <xs:complexType name="m">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <!-- recursion to allow for nested m -->
            <xs:element name="m" type="tns:m" />

            <xs:element name="area" type="tns:area" />
            <xs:element name="caption" type="tns:caption" />
            <xs:element name="circle" type="tns:circle" />
            <xs:element name="line" type="tns:line" />
            <xs:element name="outline" type="tns:line" />
            <xs:element name="lineSymbol" type="tns:line" />
            <xs:element name="text" type="tns:text" />
            <xs:element name="extrusion" type="tns:extrusion" />
            <xs:element name="symbol" type="tns:symbol" />

            <!-- outline is defined within rules to match layering -->
            <xs:element name="outline-layer" type="tns:line" />
        </xs:choice>

        <xs:attribute name="select" default="any" type="tns:selectorList" use="optional" />
        <xs:attribute name="e" type="tns:elementList" use="optional" />
        <xs:attribute name="k" type="xs:string" use="optional" />
        <xs:attribute name="v" type="xs:string" use="optional" />
        <xs:attribute name="cat" type="xs:string" use="optional" />
        <xs:attribute name="closed" default="any" type="tns:closed" use="optional" />
        <xs:attribute name="zoom-min" default="0" type="xs:unsignedByte" use="optional" />
        <xs:attribute name="zoom-max" default="127" type="xs:unsignedByte" use="optional" />
    </xs:complexType>

    <xs:complexType name="atlasRect">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="pos" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="atlas">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="rect" type="tns:atlasRect" />
        </xs:choice>
        <xs:attribute name="img" type="xs:string" use="required" />
    </xs:complexType>

    <!-- stylemenu element -->
    <xs:complexType name="stylemenu">
        <xs:sequence maxOccurs="1" minOccurs="0">
            <xs:element name="layer" maxOccurs="unbounded" minOccurs="0" type="tns:layer" />
        </xs:sequence>
        <xs:attribute name="defaultvalue" type="xs:string" use="required" />
        <xs:attribute name="defaultlang" type="xs:string" use="required" />
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <!-- tag-transform element -->
    <xs:complexType name="tag-transform">
        <xs:attribute name="k" type="xs:string" use="required" />
        <xs:attribute name="v" type="xs:string" use="optional" />
        <xs:attribute name="k-lib" type="xs:string" use="required" />
        <xs:attribute name="v-lib" type="xs:string" use="optional" />
    </xs:complexType>

    <!-- rendertheme element -->
    <xs:complexType name="rendertheme">
        <xs:sequence maxOccurs="1" minOccurs="0">
            <xs:element name="stylemenu" maxOccurs="1" minOccurs="0" type="tns:stylemenu" />

            <!-- tag definitions -->
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="tag-transform" type="tns:tag-transform" />
            </xs:choice>

            <!-- style definitions -->
            <xs:sequence maxOccurs="256" minOccurs="0">
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="style-text" type="tns:text" />
                    <xs:element name="style-symbol" type="tns:symbol" />
                    <xs:element name="style-area" type="tns:area" />
                    <xs:element name="style-line" type="tns:line" />
                    <!-- <xs:element name="style-outline" type="tns:line" /> -->
                </xs:choice>
            </xs:sequence>

            <xs:choice maxOccurs="1" minOccurs="0">
                <xs:element name="atlas" type="tns:atlas" />
            </xs:choice>

            <!-- matching rules -->
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element name="m" type="tns:m" />
            </xs:sequence>
        </xs:sequence>
        <xs:attribute name="version" type="xs:positiveInteger" use="required" />
        <xs:attribute name="map-background" default="#ffffff" type="tns:color" use="optional" />
        <xs:attribute name="base-stroke-width" default="1" type="tns:nonNegativeFloat"
            use="optional" />
        <xs:attribute name="base-text-scale" default="1" type="tns:nonNegativeFloat"
            use="optional" />
    </xs:complexType>

    <!-- root element -->
    <xs:element name="rendertheme" type="tns:rendertheme" />
</xs:schema>

=== Ebe66/Windows-Wahoo-Map-Creator-Osmosis/Themes/VTM/Others/masc4ii/vtm-element/vtm-elemnt.xml
<?xml version="1.0" encoding="UTF-8"?>
<rendertheme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" map-background="#FFFFFF"
	version="1" xmlns="http://opensciencemap.org/rendertheme"
	xsi:schemaLocation="http://opensciencemap.org/rendertheme https://raw.githubusercontent.com/mapsforge/vtm/master/resources/rendertheme.xsd">

	<stylemenu id="stylemenu" defaultvalue="BOLT_2" defaultlang="en">
      	<layer id="BOLT_2">
         	<name lang="en" value="Bolt2" />
         	<cat id="bolt2" />
         	<cat id="trails-osm" />
      	</layer>
   </stylemenu>

   <!-- region styles -->
   <!-- Footpath -->
   <style-line id="bolt2-footpath" cat="bolt2" stroke="#AAAAAA" width="0.5" dasharray="9,3" cap="butt" />
   <!-- Steps -->
   <style-line id="bolt2-steps" cat="bolt2" stroke="#000000" width="0.5" dasharray="9,9" cap="butt" />
   <!-- Cycle Trails (like MTB) -->
   <style-line id="bolt2-trail" cat="bolt2" stroke="#AAAAAA" width="1.1"/>
   <!-- Paved Tracks -->
   <style-line id="bolt2-track-paved" cat="bolt2" stroke="#AAAAAA" width="1.1" />
   <style-line id="bolt2-track-paved-cycle" use="bolt2-track-paved" />
   <!-- Non-paved tracks -->
   <style-line id="bolt2-track-raw" cat="bolt2" stroke="#555555" width="0.8" dasharray="3,3" />
   <style-line id="bolt2-track-raw-cycle" cat="bolt2" stroke="#555555" width="0.8" dasharray="6,3"/>
   <style-line id="bolt2-track-raw2" cat="bolt2" stroke="#555555" width="0.5" dasharray="3,3" />
   <style-line id="bolt2-track-raw-cycle2" cat="bolt2" stroke="#555555" width="0.5" dasharray="6,3"/>
   <!-- Tracks that don't have other info -->
   <style-line id="bolt2-track-other" cat="bolt2" stroke="#555555" width="1.1" dasharray="5,5" />
   <style-line id="bolt2-track-other-cycle" use="bolt2-track-other" stroke="#555555" />
   <!-- Paved Cycleways-->
   <style-line id="bolt2-cycle" cat="bolt2" stroke="#AAAAAA" width="1.1" />
   <!-- Elevation / contour lines-->
    <style-line id="bolt2-elevation-med-maj-z12" cat="bolt2" stroke="#550000" width="0.8"/>
	<style-line id="bolt2-elevation-med-maj-z13" cat="bolt2" stroke="#550000" width="0.64"/>
	<style-line id="bolt2-elevation-med-maj-z14" cat="bolt2" stroke="#550000" width="0.48"/>
	<style-line id="bolt2-elevation-med-maj-z15" cat="bolt2" stroke="#550000" width="0.365"/>
	<style-line id="bolt2-elevation-med-maj-z16" cat="bolt2" stroke="#550000" width="0.30"/>
	<style-line id="bolt2-elevation-med-maj-z17" cat="bolt2" stroke="#550000" width="0.24"/>
	<style-line id="bolt2-elevation-min-z13" cat="bolt2" stroke="#AA5500" width="0.64"/>
	<style-line id="bolt2-elevation-min-z14" cat="bolt2" stroke="#AA5500" width="0.48"/>
	<style-line id="bolt2-elevation-min-z15" cat="bolt2" stroke="#AA5500" width="0.365"/>
	<style-line id="bolt2-elevation-min-z16" cat="bolt2" stroke="#AA5500" width="0.30"/>
	<style-line id="bolt2-elevation-min-z17" cat="bolt2" stroke="#AA5500" width="0.24"/>
   <!-- end region -->

   <!-- region land/sea/waterways -->
   	<m e="way" k="natural" v="sea" >
     	<area cat="bolt2" fill="#00AAFF" />
   	</m>
   	<m e="way" k="natural" v="nosea">
      	<area cat="bolt2" fill="#ffffff" mesh="true" />
   	</m>
   	<m e="way" k="natural|landcover|landuse" v="wood|trees|scrub|forest">
	  	<area cat="bolt2" fill="#55FF55" fade="8" blend="12" blend-fill="#AAFFAA"/>
	  	<!--area cat="bolt2" src="icons/wood.svg" symbol-height="128" /-->
   	</m>
   	<m e="way" k="landuse" v="building">
	  	<area cat="bolt2" fill="#FFAAFF" />
   	</m>
   	<m k="amenity" v="hospital">
	  	<area cat="bolt2" fill="#FFAAFF" />
   	</m>
   	<m e="way" k="place" v="square" zoom-min="10">
      	<area cat="bolt2" fill="#FFFFFF" />
      	<!--line cat="bolt2" width="0.5" stroke="#000000" /-->
   	</m>
   	<m e="way" k="area" v="yes" zoom-min="10">
   		<m e="way" k="highway" v="pedestrian" zoom-min="10">
	      	<area cat="bolt2" fill="#FFFFFF" />
	      	<!--line cat="bolt2" width="0.5" stroke="#000000" /-->
	    </m>
   	</m>
   	<m e="way" k="area" v="yes" zoom-min="10">
   		<m e="way" k="highway" v="footway" zoom-min="10">
	      	<area cat="bolt2" fill="#AAAAAA" />
	      	<!--line cat="bolt2" width="0.5" stroke="#000000" /-->
	    </m>
   	</m>
   	<m e="way" k="leisure" v="park|nature_reserve">
      	<area cat="bolt2" fill="#AAFF55" />
	  	<!--area cat="bolt2" src="icons/park.svg" symbol-height="128" /-->
   	</m>
   	<m e="way" k="natural" v="wetland">
      	<area cat="bolt2" fill="#00FFAA" />
   	</m>
   	<m e="way" k="natural" v="beach" zoom-min="12">
      	<area cat="bolt2" fill="#FFFF00" />
   	</m>
   	<m e="way" k="man_made" v="cutline" zoom-min="14">
      	<line cat="bolt2" width="1" stroke="#AAAA55" />
   	</m>
   	<!-- endregion land/sea/waterways -->

   	<!-- region aeroway -->
   	<m e="way" k="aeroway" v="aerodrome">
		<area cat="bolt2" fill="#FFFFAA"/>
	</m>
   	<m e="way" k="aeroway" v="runway" zoom-min="10">
      	<line cat="bolt2" width="4" stroke="#AAAAFF" />
   	</m>
   	<m e="way" k="aeroway" v="taxiway" zoom-min="10">
      	<line cat="bolt2" width="2" stroke="#AAAAFF" />
   	</m>
   	<!-- endregion aeroway -->

	<!-- contour lines optimized for low-res displays interval = 10,(50/100)(Sony Xperia active)-->
	<!-- Contour lines below level 12 do not make sense because of the optimization prozessof the map-creator -->
	<!-- Level 12 + 13 do not render nice, there seems to be a bug in the renderer -->
	<!-- contour lines level 12 -->
	<m e="way" k="contour_ext" zoom-min="12" zoom-max="12">
		<m e="way" k="contour_ext" v="elevation_medium|elevation_major">
			<!--line use="bolt2-elevation-med-maj-z12"/-->
		</m>
	</m>
	<!-- contour lines level 13 -->
	<m e="way" k="contour_ext" zoom-min="13" zoom-max="13">
		<m e="way" k="contour_ext" v="elevation_minor">
			<line use="bolt2-elevation-min-z13"/>
		</m>
		<m e="way" k="contour_ext" v="elevation_medium|elevation_major">
			<line use="bolt2-elevation-med-maj-z13"/>
		</m>
	</m>
	<!-- contour lines level 14-->
	<m e="way" k="contour_ext" zoom-min="14" zoom-max="14">
		<m e="way" k="contour_ext" v="elevation_minor">
			<line use="bolt2-elevation-min-z14"/>
		</m>
		<m e="way" k="contour_ext" v="elevation_medium|elevation_major">
			<line use="bolt2-elevation-med-maj-z14"/>
		</m>
	</m>
	<!-- contour lines level 15-->
	<m e="way" k="contour_ext" zoom-min="15" zoom-max="15">
		<m e="way" k="contour_ext" v="elevation_minor" zoom-max="15">
			<line use="bolt2-elevation-min-z15"/>
		</m>
		<m e="way" k="contour_ext" v="elevation_medium|elevation_major">
			<line use="bolt2-elevation-med-maj-z15"/>
			<m e="way">
				<!--pathText k="ele" font-style="bold" font-size="8" fill="#000000" stroke="#ffffff" stroke-width="1.0"/-->
			</m>
		</m>
	</m>
	<!-- contour lines level 16 -->
	<m e="way" k="contour_ext" zoom-min="16" zoom-max="16">
		<m e="way" k="contour_ext" v="elevation_minor">
			<line use="bolt2-elevation-min-z16"/>
		</m>
		<m e="way" k="contour_ext" v="elevation_medium|elevation_major">
			<line use="bolt2-elevation-med-maj-z16"/>
			<m e="way">
				<!--pathText k="ele" font-style="bold" font-size="8" fill="#000000" stroke="#ffffff" stroke-width="1.0"/-->
			</m>
		</m>
	</m>
	<!-- contour lines level 17 and above -->
	<m e="way" k="contour_ext" zoom-min="17">
		<m e="way" k="contour_ext" v="elevation_minor">
			<line use="bolt2-elevation-min-z17"/>
		</m>
		<m e="way" k="contour_ext" v="elevation_medium|elevation_major">
			<line use="bolt2-elevation-med-maj-z17"/>
			<m e="way">
				<!--pathText k="ele" font-style="bold" font-size="8" fill="#000000" stroke="#ffffff" stroke-width="1.0"/-->
			</m>
		</m>
	</m>

	<!-- region lakes/reservoirs/peers over contour lines -->
	<m e="way" k="waterway" v="river|canal">
      	<line cat="bolt2" width="1" stroke="#00AAFF" />
      	<pathText display="always" cat="bolt2" fill="#0000AA" k="name" font-family="sans_serif" font-style="bold" priority="2" size="16" stroke="#ffffff" stroke-width="3.0" zoom-min="14" />
   	</m>
   	<m e="way" k="waterway" v="stream" zoom-min="14">
      	<line cat="bolt2" width="0.7" stroke="#00AAFF" />
   	</m>
   	<m e="way" k="waterway" v="river|riverbank|canal" closed="yes">
		<area cat="bolt2" fill="#00AAFF"/>
	</m>
	<m e="way" k="landuse" v="reservoir">
		<area cat="bolt2" fill="#00AAFF"/>
	</m>
	<m e="way" k="natural" v="water">
		<area cat="bolt2" fill="#00AAFF"/>
	</m>
	<m e="way" k="man_made" v="pier" zoom-min="12">
      	<line cat="bolt2" width="1" stroke="#FFFFAA" />
   	</m>
   	<m e="way" k="area" v="yes" zoom-min="12">
   		<m e="way" k="man_made" v="pier" zoom-min="12">
	      	<area cat="bolt2" fill="#FFFFAA" />
	    </m>
   	</m>
   	<!-- end region lakes/reservoirs/peers over contour lines -->

   	<!-- region military -->
   	<m e="way" k="landuse" v="military" zoom-min="10">
   		<line cat="bolt2" width="1" stroke="#FF5555" />
		<area cat="bolt2" src="icons/stripesDown.svg" symbol-height="32" />
	</m>
	<m e="way" k="area" v="yes" zoom-min="10">
		<m e="way" k="landuse" v="military" zoom-min="10">
   			<line cat="bolt2" width="1" stroke="#FF5555" />
			<area cat="bolt2" src="icons/stripesDown.svg" symbol-height="32" />
		</m>
	</m>
   	<!-- endregion military -->

   	<!-- boundary -->
   <m k="admin_level">
      <m v="2">
      	 <m zoom-min="3">
         	<line stroke="#AA00AA" width="2.5" cap="butt" />
         </m>
      </m>
   </m>
   <!-- endregion boundary -->

   	<!-- region tunnels: todo: bring in foreground, before <m e="way" k="natural|landcover|landuse" v="wood|trees|scrub|forest"> -->
   	<m e="way" k="tunnel" v="true|yes" zoom-min="8">
   		<m e="way" k="highway" v="service" zoom-min="13">
   		   <line cat="bolt2" stroke="#555555" width="1.0" dasharray="15,10" cap="butt" />
           <line cat="bolt2" stroke="#AAAAAA" width="0.6" dasharray="15,10" cap="round" />
        </m>
      	<m e="way" k="highway" v="residential|living_street|road|unclassified" zoom-min="13">
      	   <line cat="bolt2" stroke="#000000" width="2.3" dasharray="10,7" cap="butt" />
